### PR TITLE
feature/econometrics: Added Variance Inflation Factor

### PR DESCRIPTION
**Pull request by HemuManju**
# Description

Hello Everyone,

I hope this message finds you well. 

In this pull request, I have included the following models for econometrics:

- Variance Inflation Factor (VIF)

## How has this been tested?
* I have followed the test structure, like the technical analysis (ta) extension. 
* All the tests (API and Python) are included in the *integration* folder.
- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works
- [x] Check any related reports

## Checklist:
- [x] I have adhered to the GitFlow naming convention, and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name.`
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added, make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

## Others
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.

⚠️ Disclaimer: This is a rewrite of the original openbb_terminal feature in v4 SDK. Credit goes to its original authors.

### CODE REVIEW

**Comment by jmaslek** [comment]
Thanks for bringing this one over!  I left a comment in the code, but it would be nice to be able to associate a variable with the vif in the output, so returning the column as well in the df would be my initial thoughts...

**Comment by HemuManju** [comment]
@jmaslek If I understand correctly, the output should be something similar to `f{column_name}_vif_value` instead of just returning a list of vif values?

**Comment by jmaslek** [comment]
I think we can return a dataframe where the columns are the columns of the input and the values are the corresponding big value.

**Comment by HemuManju** [comment]
Now the result is a data frame with columns from input and values are VIF values.

**Review by jmaslek — APPROVED** [review]
Sorry for the delay but this looks good o my end!

**Pull request merged**
