### PR TITLE
Option Payoff Diagrams

### PR DESCRIPTION
**Pull request by colin99d**
Creates a payoff diagram for an underlying asset (stock) and an unlimited number of derivatives added to it. Can choose any strike price available, choose between a put and call and between buying or selling the derivative.

**Note:** I have NOT added this to the website yet because I am assuming it will get torn up first (:

### CODE REVIEW

**Comment by jmaslek** [comment]
If you enter `payoff` without having ticker and exp, the terminal crashes, so you should add a check first.

**Comment by jmaslek** [comment]
So if I do 

```(✨) (options)>(payoff)> add -k 150
list index out of range 
```
(AAPL - exp 2, 150 is in list)

**Comment by colin99d** [comment]
> So if I do 
> 
> 
> 
> ```
> 
> (✨) (options)>(payoff)> add -k 150
> 
> list index out of range 
> 
> ```
> 
> (AAPL - exp 2, 150 is in list)

So when you type list you are supposed to use the numbers on the left after -k, not the actual strike price.

**Comment by jmaslek** [comment]
I see.  I was able to do `add -k 10` so there should be some distinguishing between selecting a strike price and a strike index

**Comment by colin99d** [comment]
> So @DidierRLopes can chime in here.  The way this currently is really goes away from the MVC we have been aiming for.  We should have specific files for payoff_view/payoff_model that do the usual stuff, that way we can import the functions into a Jupyter notebook for example.  
> 
> 
> 
> 

Should I move the data getting functions to a model and the matplotlib stuff to a view?

**Comment by jmaslek** [comment]
Yeah. That was we have consistency across repo and it helps with the "importability"

**Comment by DidierRLopes** [comment]
> > So @DidierRLopes can chime in here.  The way this currently is really goes away from the MVC we have been aiming for.  We should have specific files for payoff_view/payoff_model that do the usual stuff, that way we can import the functions into a Jupyter notebook for example.
> 
> Should I move the data getting functions to a model and the matplotlib stuff to a view?

Exactly. You can read more about the code structure here: https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md.

**Comment by colin99d** [comment]
> So @DidierRLopes can chime in here. The way this currently is really goes away from the MVC we have been aiming for. We should have specific files for payoff_view/payoff_model that do the usual stuff, that way we can import the functions into a Jupyter notebook for example.

Awesome! Got this updated.

**Comment by colin99d** [comment]
> Some comments. Overall looks great!
> 
> I think you forgot to add the new line after each command as well.
> 
> And I couldn't figure out the add/rmv commands, but I'm smooth brain ahah

So when you type list it gives the index on the left and then the corresponding call/put on the right. You use the index on the left to add/rmv

**Comment by colin99d** [comment]
> I think you still forgot the "." in ">. payoff"
Screen Shot 2021-10-10 at 4 51 23 PM
I am seeing it.

**Comment by colin99d** [comment]
> > > I think you still forgot the "." in ">. payoff"
> > 
> > 
> > Screen Shot 2021-10-10 at 4 51 23 PM
> > I am seeing it.
> 
> Yes, I meant the opposite :p We usually don't have the "."

Ohhhhh. Lol

**Pull request merged**
