### PR TITLE
Rename `index.market` to `index.price.historical`

### PR DESCRIPTION
**Pull request by dot-agi**
To maintain consistency across all other extensions.

# Changelog
* Adds a `price` router inside `openbb-index` which contains the `historical` endpoint
* Renames `market_indices.py` files to `index_historical.py`
* Renames `MarketIndices` model to `IndexHistorical`
* Modifies `<openbb_provider>.model.market_indices` to `<openbb_provider>.model.index_historical` in provider model imports
* Modifies fetcher tests to use `IndexHistorical` fetcher
* Renames cassette files to use `index_historical` to prevent breaking tests by re-recording
* Modifies `openbb-index` tests to use the modified endpoint name

### CODE REVIEW

**Comment by IgorWounds** [comment]
@andrewkenreich

**Review by andrewkenreich — APPROVED** [review]

**Comment by deeleeramone** [comment]
Here's a general question:

Is the `price` level necessary, or can we just have `index.historical`? Technically, it's not a price but some type of "points" system that will vary.

**Comment by the-praxs** [comment]
Since we added the deprecation feature this PR will be closed in favor of that one. 

I will re-do the renaming, but please let me know whether it should be `index.historical` or `index.price.historical`.

**Review by IgorWounds — APPROVED** [review]

**Comment by the-praxs** [comment]
Closed in favour of #5962

**Pull request closed without merging**
