### PR TITLE
Added Example Notebook Demonstrating Fundamental Analysis with OpenBB

### PR DESCRIPTION
**Pull request by SahiLmb**
**Description:**

This PR covers a detailed fundamental analysis of Apple (AAPL), leveraging various financial metrics and macroeconomic indicators. Highlights include:

- Financial Performance: Analyzed revenue, profit, and cash flow trends.

- Balance Sheet: Evaluated debt, assets, and liquidity ratios.

- Financial Ratios: Assessed current, quick, cash ratios, P/E ratio, and dividend yield.

- Macroeconomic Context: Integrated GDP growth, unemployment rates, and interest rates to gauge economic impact on Apple.

Testing Done:

Run all the cells in the notebook successfully without warnings and errors.

Reviewer Notes
I would appreciate any constructive feedback on this PR. If there are any areas for improvement, please share your insights by raising the issues. This will help in refining the changes. Thank you.

closes https://github.com/OpenBB-finance/OpenBB/issues/6706

### CODE REVIEW

**Comment by SahiLmb** [comment]
Hello @piiq can you please review my PR and let me know if there are any changes to be made or it's good to be merged. Thank you.

**Comment by piiq** [comment]
Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions.
Thanks

**Comment by SahiLmb** [comment]
Sorry for the last day submission and Thank you, will try next time to submit it at the earliest.

**Comment by SahiLmb** [comment]
> Hi, hacktoberfest is over. We're not reviewing or accepting any more oss.gg submissions. Thanks

Sorry for the last day submission and Thank you, will try next time to submit it at the earliest.

**Pull request closed without merging**
