### PR TITLE
feat: Article comparing OpenBB to other financial tools

### PR DESCRIPTION
**Pull request by shreykx**
image

I wrote a story on **Medium** about this. 

**Link to medium: https://medium.com/@shreykx/collating-openbb-with-others-e826b062e19b**

### CODE REVIEW

**Comment by shreykx** [comment]
image

**Comment by piiq** [comment]
Hi, you have a few defects in your post:

1. The weird formatting when every first letter of the word is bold
2. Factual errors like Koyfin not having a paid plan (they do) and OpenBB being completely open source (while OpenBB has a strong open source foundation not all components of OpenBB are open source)
3. Your interpretation of open source if very misleading. Open source builds transparency, but it doesn’t guarantee instant trust or rapid fixes, community contributions vary, and effective support depends on active maintenance and realistic expectations.

Please address these if you want this submission to be accepted.

**Comment by shreykx** [comment]
I'm gonna fix it

**Comment by shreykx** [comment]
1st fix (weird formatting) - 
image

2nd fix (koyfin+openbb)

#koyfin 
image

# openbb is not completely open-source


i think your readme.md needs an update 😅
image
still corrected-
image



3rd fix (facts)-

image

**Comment by shreykx** [comment]
@piiq here you go

**Comment by piiq** [comment]
I'm not accepting this, sorry

If you will make another attempt - please proof-read what you are publishing and make sure you're not deleting mentions of other contributors in the PR itself (like you've done in this PR)

**Pull request closed without merging**
