### PR TITLE
Added setup_OpenBB.bat, a batch file to automate full setup in Windows.

### PR DESCRIPTION
**Pull request by Thepathakarpit**
# Pull Request the OpenBB Platform

## Description

-Summary:  
 - Automated the setup, installation, and dependencies for the OpenBB Platform.
  - Checks for the presence of Python and Pip, and installs them if they are not found.
  - Installs the OpenBB Platform, OpenBB Platform CLI, and required dependencies.
  - Runs the OpenBB Platform after the setup is complete.
 
- It will make it super easy for users to complete the setup and run the project. After all it only takes one command to run it.

Steps to run: 
1. Save the script to a file, openbb_setup.bat
2. Open the command prompt or PowerShell
3. Run the script by typing openbb_setup.bat and pressing Enter

Thank you

### CODE REVIEW

**Comment by deeleeramone** [comment]
Hi there, thanks very much for the PR. We are currently working on an installer that will accomplish this task, and more. We don't like the idea of touching the system Python, so the installer will load and setup a full setup, along with additional tooling. You can checkout PR #6587 to see the setup scripts.

**Comment by Thepathakarpit** [comment]
> Hi there, thanks very much for the PR. We are currently working on an installer that will accomplish this task, and more. We don't like the idea of touching the system Python, so the installer will load and setup a full setup, along with additional tooling. You can checkout PR #6587 to see the setup scripts.

Yes it is great but don't you think this PR script is way simpler and intuitive for users to use. The simplicity will help you with people who don't want to read full procedure but just a friend sends them a batch file or they copy paste it and on running it does everything. Consider adding this as a feature too, will help beginners explore too.

**Comment by deeleeramone** [comment]
> Yes it is great but don't you think this PR script is way simpler and intuitive for users to use. The simplicity will help you with people who don't want to read full procedure but just a friend sends them a batch file or they copy paste it and on running it does everything. Consider adding this as a feature too, will help beginners explore too.

Sorry, this is not appropriate script to add to the repository. Installing Python, and Python packages, directly to the system does not follow best practices, and in many cases will create problems for the user and/or break other things they already have configured.

I do appreciate your desire to streamline the process for less technical users, however a signed installer is a much more secure and reputable way to distribute or share this package.

**Comment by Thepathakarpit** [comment]
> > Yes it is great but don't you think this PR script is way simpler and intuitive for users to use. The simplicity will help you with people who don't want to read full procedure but just a friend sends them a batch file or they copy paste it and on running it does everything. Consider adding this as a feature too, will help beginners explore too.
> 
> Sorry, this is not an appropriate script to add to the repository. Installing Python, and Python packages, directly to the system does not follow best practices, and in many cases will create problems for the user and/or break other things they already have configured.
> 
> I do appreciate your desire to streamline the process for less technical users, however a signed installer is a much more secure and reputable way to distribute or share this package.

Okay no issues do let me know if in future you need something like this. Had fun doing this task for the project. Thank you.

**Pull request closed without merging**
