### PR TITLE
Added file : Created Notebook for Portfolio Optimization Using Modern Portfolio Theory (Hacktoberfest)

### PR DESCRIPTION
**Pull request by ambroseikpele**
Linked: #6708

### CODE REVIEW

**Comment by jmaslek** [comment]
Hey!  Welcome to the OpenBB Contributor club and thanks for taking the time to contribute.

I am going to just give some of my thoughts on this.  

I was hoping to see a bit more of the "what is going on with mpt/mvo".  You have a brief sentence, but I don't see the problem framed at all, i.e a section on what we are doing with MVO -- and it is impossible not to describe without a few formulas.

Great usage of openbb, and the list allows people to define anything they want to look at.

When you go into setting up the problem, I was expecting to see some explanation of the covraiance, especially when you use a shrinkage method.  Lets be more explicit about what the notebook does and why.

Same with the actual calculations.  PYPFOPT is a great library (shoutout rob), but there is no explanation of what the efficient frontier is or what and why you use CLA.

Also in the intro you say maximize returns while minimizing risk (ie I was thinking you would go sharpe,=), but then you take min volatility, so slight discontinuity.  

Very nice visualization.

In general, I was just hoping for some more explanation of what was going on here.  Thoughts?

**Comment by jmaslek** [comment]
Also you should update the file in oss.gg folder

**Comment by ambroseikpele** [comment]
Thank you for feedback @jmaslek 

I have updated the Notebook taking your feedback into account

**Comment by ambroseikpele** [comment]
Also, about editing the oss.gg folder, which of the files in the code_side_quests folder should I add my details. The closest seems to be 1-openbb-integration.md ; Side Quest: Integrate OpenBB into a dashboard or web application, but i am confused because the issue requested for a Notebook and not a dashboard neither a web app.

thanks

**Comment by jmaslek** [comment]
> Also, about editing the oss.gg folder, which of the files in the code_side_quests folder should I add my details. The closest seems to be 1-openbb-integration.md ; Side Quest: Integrate OpenBB into a dashboard or web application, but i am confused because the issue requested for a Notebook and not a dashboard neither a web app.
> 
> thanks

Yeah that was my mistake - I dont think that was needed for this.

**Comment by ambroseikpele** [comment]
> /award 300

Thank you

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
