### PR TITLE
feat: Write a Use-Case Blog for OpenBB in Fundamental Analysis

### PR DESCRIPTION
**Pull request by Khaan25**
My submission for Side Quest: Write a Use-Case Blog for OpenBB in Fundamental Analysis (Points: 300 Points)

I've referred to [openbb docs](https://docs.openbb.co/platform/reference/equity/fundamental/balance). Hope it's beneficial for people to effectively and easily use it :)

### CODE REVIEW

**Comment by piiq** [comment]
Hi, you have factual errors in your post

1. OpenBB does not stand for open bloomberg.
2. You are mixing up the screenshots from the OpenBB Terminal website and the OpenBB Platform python interface. Those are different tools in the OpenBB ecosystem. If you are using screenshots from the website, don't tell ppl to install is with python, it's a web-app that doesn't require installation, etc.

Please correct these errors if you want the submission to be accepted

**Comment by Khaan25** [comment]
Heyy, Thank you for the feedback.

1. I found the name in testimonials 
image

2. Right. I'll correct that up.

**Comment by piiq** [comment]
> 1. I found the name in testimonials

In the testimonials it does not say the OpenBB stands for open bloomberg and it does not

**Comment by Khaan25** [comment]
I thought BB stands for that :)

Open + Bloomberg

No worries, I'll fix that up and let you know

**Comment by Khaan25** [comment]
Heyyy @piiq , I've updated the article, would you mind having a look? I've added an example with Copilot as well, how you can use copilot to save time. :)

**Comment by Khaan25** [comment]
Hey, any update :)

**Review by piiq — APPROVED** [review]

**Pull request merged**
