### PR TITLE
Add a Dockerfile for easy platform-api install

### PR DESCRIPTION
**Pull request by jmaslek**
Based off of #6749 

This just adds a simple dockerfile for integrating openbb[all] with pro

### CODE REVIEW

**Review by IgorWounds — APPROVED** [review]

**Comment by jmaslek** [comment]
god i need to rebase lol

**Review by deeleeramone — CHANGES_REQUESTED** [review]
Docker works, but I'm not able to connect this in Terminal Pro. 

Screenshot 2024-10-08 at 11 59 27 AM

**Comment by deeleeramone** [comment]
@jmaslek Do we want `--login` flag so they can add their Hub credentials? What about the mapping to `~/.openbb_platform`?

**Comment by jmaslek** [comment]
> @jmaslek Do we want `--login` flag so they can add their Hub credentials?
> 
> What about the mapping to `~/.openbb_platform`? - I had some out-of-order syntax when launching the container.

So I added login - good call.  (And yeah you saw that the container has to map to localhost).

You can mount the image if you wanna persist anything
```
docker run -it -p 6900:6900 -v ~/.openbb_terminal:/app/.openbb_platform ghcr.io/openbb-finance/platform-api
```

**Comment by deeleeramone** [comment]
> > @jmaslek Do we want `--login` flag so they can add their Hub credentials?
> > What about the mapping to `~/.openbb_platform`? - I had some out-of-order syntax when launching the container.
> 
> So I added login - good call. (And yeah you saw that the container has to map to localhost).

Ok, so login does not work @jmaslek. 

termios.error: (25, 'Inappropriate ioctl for device')

```sh
/usr/local/lib/python3.10/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.


Enter your personal access token (PAT) to authorize the API and update your local settings.
Skip to use a pre-configured 'user_settings.json' file.
Press Enter to skip or copy (entered values are not displayed on screen) your PAT to the command line: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/getpass.py", line 69, in unix_getpass
    old = termios.tcgetattr(fd)     # a copy to save
termios.error: (25, 'Inappropriate ioctl for device')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/openbb-api", line 5, in <module>
    from openbb_platform_api.main import main
  File "/usr/local/lib/python3.10/site-packages/openbb_platform_api/main.py", line 48, in <module>
    current_settings = get_user_settings(login, CURRENT_USER_SETTINGS, USER_SETTINGS_COPY)
  File "/usr/local/lib/python3.10/site-packages/openbb_platform_api/utils/api.py", line 83, in get_user_settings
    pat = getpass.getpass(
  File "/usr/local/lib/python3.10/getpass.py", line 91, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/local/lib/python3.10/getpass.py", line 126, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/local/lib/python3.10/getpass.py", line 148, in _raw_input
    raise EOFError
EOFError
```

**Comment by deeleeramone** [comment]
> Gonna need more info -- can't reproduce. Looks like potentially an issue with something in the json. What did you run ?

lol. I can't reproduce anymore either..

**Review by deeleeramone — APPROVED** [review]

**Comment by o6uoq** [comment]
Can this please be added to the documentation? Having an easy way to get up and running via Docker would be great!

**Pull request merged**
