### PR TITLE
fix

### PR DESCRIPTION
**Pull request by ArtificialZeng**
# Pull Request OpenBB

Please go the the `Preview` tab and select the appropriate PR sub-template:

* [OpenBB Platform](?expand=1&template=platform_pull_request_template.md)
* [OpenBB Platform CLI](?expand=1&template=terminal_pull_request_template.md)
* [OpenBB Developers](?expand=1&template=obb_developer_pull_request_template.md)

### CODE REVIEW

**Review by DidierRLopes — APPROVED** [review]

**Comment by piiq** [comment]
@ArtificialZeng thanks for this grammar fix.

If you would like this to be merged you would need to follow the contributing guidelines.
https://docs.openbb.co/platform/developer_guide/github#branch-naming-conventions

The 2 things missing for this PR are:

1. Point the PR to develop, not main
2. Start the branch name with a `buffix/` prefix

**Comment by ArtificialZeng** [comment]
> @ArtificialZeng thanks for this grammar fix.
> 
> If you would like this to be merged you would need to follow the contributing guidelines. https://docs.openbb.co/platform/developer_guide/github#branch-naming-conventions
> 
> The 2 things missing for this PR are:
> 
> 1. Point the PR to develop, not main
> 2. Start the branch name with a `buffix/` prefix

all done in this pr:
https://github.com/OpenBB-finance/OpenBB/pull/6696

**Comment by piiq** [comment]
closing in favour of #6696

**Comment by ArtificialZeng** [comment]
> closing in favour of #6696

pls reopen this one. and I have done all the review you requested

**Comment by ArtificialZeng** [comment]
> closing in favour of #6696

only this one doesn't have any conflicts.

**Comment by ArtificialZeng** [comment]
> closing in favour of #6696



> @ArtificialZeng thanks for this grammar fix.
> 
> If you would like this to be merged you would need to follow the contributing guidelines. https://docs.openbb.co/platform/developer_guide/github#branch-naming-conventions
> 
> The 2 things missing for this PR are:
> 
> 1. Point the PR to develop, not main
> 2. Start the branch name with a `buffix/` prefix

can you reopen this one？

**Comment by piiq** [comment]
Sorry @ArtificialZeng, but you still need to do the things mentioned in my message

1. Point the PR to develop, not main
2. Start the **branch name** with a buffix/ prefix. This PR is pointing to main and the branch name is called `patch-1` without a prefix. We can't merge into main, there is a security rule that prevents this. You should go to your fork, sync your develop branch with upstream (our develop branch), create a branch off develop that would be called something like `bugfix/spelling`, then commit the changes into that branch and create a PR. This way it will work.

**Pull request closed without merging**
