### PR TITLE
[Feature] Add Finviz Screener Presets (V3 Compatible)

### PR DESCRIPTION
**Pull request by deeleeramone**
1. **Why**?:

    - Porting a popular Terminal/V3 feature to Platform.
    - See #6586 for discussion and implementation requirements.

2. **What**?:

Below is copied from the `README.md`

## Screener

The screener is a faithful replication of the public-facing stock screener - https://finviz.com/screener.ashx?

Some options are directly accessible through the function parameters, all others are exposed via `presets` or `filters_dict`.
The filters list below are exposed in the function, with choices visible in the docstring:

- `exchange`
- `index`
- `sector`
- `industry`
- `mktcap`
- `recommendation` (analyst's mean score from 1-5)
- `signal` (same as the "Signal" on the Finviz page)

When the function is run without any parameters, it will default to the "top_gainers" signal.

```python
res = obb.equity.screener(provider="finviz")
```

### Metric

The `metric` parameter defines the type of data fields to return. Choices are:

- `overview`
- `ownership`
- `performance`
- `techincal`
- `valuation`

Default is, "overview".

```
res = obb.equity.screener(provider="finviz", metric="performance")
```

### Preset Files

Presets can be created and customized in the "OpenBBUserData" folder. Template and default presets are created on the first run of the function.

Files are loaded on run time, changes are effective without restarting the Python interpreter.

The `preset` parameter will override all others, except `metric` and `limit`.

Run the function to create the template and default presets in your `OpenBBUserData` folder.

Presets from the legacy OpenBB Terminal will continue to work, simply move your presets into the folder below.

```python
res = obb.equity.screener(provider="finviz", index="nasdaq")
```

Then find the presets here: `$HOME/OpenBBUserData/presets/finviz`

```python
res = obb.equity.screener(provider="finviz", preset="short_squeeze")
```

### Filters Dict

The `filters_dict` parameter acts as an alternative to `preset`, accepting a dictionary or JSON encoded string.

```python
res = obb.equity.screener(provider="finviz", filters_dict={"Index": "NASDAQ 100"})
```

Or as a JSON:

```python
res = obb.equity.screener(provider="finviz", filters_dict='{"Index": "NASDAQ 100"}')
```

When using the Fast API, this is sent in the request body.

### Error Messages

All parameters are validated, incorrect keys and choices will raise an error with information to help correct. For example:

```python
obb.equity.screener(provider="finviz", filters_dict='{"Index": "NASDAQ"}')
```

```console
Invalid filter option 'NASDAQ'. Possible filter options: ['Any', 'S&P 500', 'NASDAQ 100', 'DJIA', 'RUSSELL 2000']
```

3. **Impact**:

    - The function will attempt to read/write to the file system in order to populate the user data folder.
    - Makes the function's docstring substantially larger.

4. **Testing Done**:

    - Unit/integration tests.
    - CLI

5. **Reviewer Notes**:

    - To test the function directly from the Swagger docs, the contents of the "Request Body" must be deleted.

### CODE REVIEW

**Review by IgorWounds — APPROVED** [review]

**Comment by mmistroni** [comment]
Brilliant! works as a charm! when will be available via pip? i guess i'll have to install  a new version of openbb-finviz?
Also, will this screener be automaticaly exposed to the OBB REST API? if not could you advise where do i need to do changes as i am planning to leverage the OBB REST?
thanks

**Comment by yolotrader** [comment]
@IgorWounds I'm getting the following error when running the preset:
Screenshot 2024-08-29 at 10 19 54 AM

Could you pls take a look?

Thank you for this great work, btw!

**Comment by mmistroni** [comment]
uh, thats my preset :(

i'll have a look at it tomorrow morning.... sorry about this

Kind regards
  Marco

**Comment by mmistroni** [comment]
@yolotrader  that's just a warning, which is controlled by your preferences
if you print out the result you will see data
Note, you will see this error for any presets you use..

hth

**Comment by yolotrader** [comment]
@mmistroni thanks!

**Pull request merged**
