### PR TITLE
add: M&A impact example notebook

### PR DESCRIPTION
**Pull request by NabidAkhtar**
# Pull Request the OpenBB Platform

## Description

- [x] Summary of the change/ bug fix: Added a new Jupyter notebook example demonstrating how to perform M&A impact analysis using OpenBB's historical data functions. This notebook analyzes stock performance of companies around M&A announcements, with visualizations and a summary report.
- [x] Link #6714 , if applicable.
- [x] Screenshot of the feature or the bug before/after fix, if applicable: 
image
- [x] Relevant motivation and context: This example notebook provides OpenBB users with a practical demonstration of M&A impact analysis, showcasing OpenBB’s data retrieval and analysis capabilities.
- [x] List any dependencies that are required for this change: Added matplotlib to the installation cell to ensure compatibility for users outside of Colab, where it may not be pre-installed.

## How has this been tested?

- Please describe the tests that you ran to verify your changes: The notebook was run in a Jupyter environment to confirm that all cells execute as expected and produce correct outputs.
- Please provide instructions so we can reproduce: To reproduce, run the notebook in a Jupyter environment with OpenBB installed.
- Please also list any relevant details for your test configuration: Verified data retrieval, accurate calculations, and expected visualizations.

Commands Execution Verification: Not applicable for this notebook addition.

- [ ] Ensure all unit and integration tests pass.
- If you modified/added command(s):
  - [ ] Ensure the command(s) execute with the expected output.
    - [ ] API.
    - [ ] Python Interface.
  - [ ] If applicable, please add new tests for the command (see [CONTRIBUTING.md](/openbb_platform/CONTRIBUTING.md) to leverage semi-automated testing).
- If a new provider was introduced or a new fetcher was added to an existing provider:
  - [ ] Ensure the existing tests pass.
  - [ ] Ensure the new provider and/or fetcher is stable and usable.
  - [ ] If applicable, please add new tests for the provider and/or fetcher (see [CONTRIBUTING.md](/openbb_platform/CONTRIBUTING.md) to leverage semi-automated testing).
- If a new provider or extension was added:
  - [ ] Update the list of [Extensions](/openbb_platform/EXTENSIONS.md).
  - [ ] Update the list of [Providers](/openbb_platform/PROVIDERS.md).
  - [ ] If it's a community extension or provider, update the [integration tests GitHub Action workflow](/.github/workflows/platform-api-integration-test.yml).

## Checklist

- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] I ensure that I am following the [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBB/blob/main/CONTRIBUTING.md).
  - [ ] (If applicable) I have updated tests following [these guidelines](/openbb_platform/CONTRIBUTING.md#qa-your-extension).

</details>

### CODE REVIEW

**Comment by piiq** [comment]
resolves https://github.com/OpenBB-finance/OpenBB/issues/6714

**Comment by piiq** [comment]
Hi, 3 suggestions

1. The openbb package does not bring in matplotlib and seaborn so you will need to update the installation instruction cell to specify that matplotlib and seaborn (?) need to be installed for this notebook to run. It currently works on colab because google pre-installes both of these packages into the default colab environment.
2. When providing a link for the "run in colab" badge - please reference the notebook in the repo, not in your personal google drive
3. seaborn is not used in the notebook so it would make sense to remove the import and remove the mention of the requirement to install it

Thanks

**Comment by NabidAkhtar** [comment]
@piiq  I’ve implemented all suggested changes:
Added matplotlib in the installation instructions to ensure compatibility across environments.
Updated the Colab link to reference the repository location directly.
Removed the unused seaborn import.
Thank you for the feedback! Please review when you have a chance.

**Comment by piiq** [comment]
Thanks 2 more suggestions

1. In the repo we have the the convention to use "symbol" instead of "ticker". To make it more aligned please consider also using "symbol"
2. In the report and the chart you can use the actual symbol instead of "ACQUIRER_TICKER" and "TARGET_TICKER" strings and the actual announcement date instead of "ANNOUNCEMENT_DATE" string

**Comment by piiq** [comment]
Once this is addressed I am happy to approve and merge this notebook
Thanks

**Comment by NabidAkhtar** [comment]
@piiq  I’ve implemented the additional changes:
- Replaced "ticker" with "symbol" throughout the notebook for consistency with repo conventions.
- Updated `plot_ma_analysis` and `generate_ma_report` to display the actual symbols and announcement date instead of placeholders.

Please review the changes at your convenience. Thanks for the guidance!

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
