### PR TITLE
[🕹️]Added the notebook for Backtesting Momentum Strategies

### LINKED ISSUE #6712: [🕹️] Create a Notebook for Backtesting Momentum Strategies
# 📄 Task
  
Build a Jupyter notebook that backtests a momentum trading strategy using OpenBB’s historical data.

---

### 📋 Requirements:

1. **Template**: Start by copying the [example template notebook](https://github.com/OpenBB-finance/OpenBB/blob/develop/examples/COMMUNITY_EXAMPLE_TEMPLATE.ipynb).
2. **Content**: 
   - Give your notebook a meaningful name.
   - Fill in the details in the template, including the notebook title, description, your GitHub username, the notebook name in the Google Colab button, and any additional sections relevant to the task.
   - Write code that uses OpenBB's features to model risk-return tradeoffs.
   - If your notebook requires additional dependencies, please specify those.
3. **Testing**: Ensure that all cells in the notebook run successfully and produce the intended results.
4. **Documentation**: Comment your code and add markdown cells where necessary to provide explanations for the analysis.
5. **Output**: The final notebook should be added to the `examples` folder in this repository.

### 💡 Tips:
  
- Refer to the [OpenBB Documentation](https://docs.openbb.co/) for guidance on using OpenBB features.

### 📬 Submission:

- Follow the submission instructions [here](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg).
- Open a Pull Request (PR) to the `develop` branch.
- Include a brief description of your notebook and the analysis it performs in the PR body.

Happy hacking!

### PR DESCRIPTION
**Pull request by SanchitMahajan236**
1. **Why**? (1-3 sentences or a bullet point list):

- To provide users with the ability to backtest momentum-based trading strategies within the OpenBB framework.
- This enhancement allows for historical performance evaluation, helping traders identify profitable patterns.
- Addresses user requests for more sophisticated strategy testing tools.

2. **What**? (1-3 sentences or a bullet point list):

- Added functionality to backtest momentum trading strategies using historical price data.
- Implemented momentum indicators such as RSI and Moving Averages to simulate trades based on defined strategy rules.
- Integrated results visualization for clear performance insights.

3. **Impact** (1-2 sentences or a bullet point list):

- Expected to enhance user capability to test and refine momentum strategies, leading to more informed trading decisions.
- Minimal impact on system performance, with backtesting execution time expected to increase by ~5%.
- Impact score: 8

    > [!TIP]
    > Refer to the Impact Analysis confluence (internal) document for more information.

4. **Testing Done**:

- Validated using historical stock price data across various market conditions.
- Simulated multiple momentum-based strategies to ensure accuracy and reliability of results.

Closes #6712

### CODE REVIEW

**Comment by SanchitMahajan236** [comment]
Hi @jmaslek, please review my PR.

**Comment by jmaslek** [comment]
Can you supress the pandas warnings then I will approve and merge

**Comment by SanchitMahajan236** [comment]
Hey @jmaslek, I have addressed the pandas warning. You can review the PR.

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
