### PR TITLE
Added raw stock data #817

### PR DESCRIPTION
**Pull request by colin99d**
Adds the ability to view, sort, and customize raw stock data. The data can also be exported.

### CODE REVIEW

**Comment by jmaslek** [comment]
Nice.  I think it may be a simpler implementation if you just add this to the main stocks menu (where candle is) and you can just use the self.stock data.

**Comment by jmaslek** [comment]
> Was about to say the same. I don't think TA is the right menu to contain this. I would just have it in candle directly and allow a --raw command. Think is the right thing to do. At least that's what we've been doing for all other commands when we want raw data from a plot we see or so

I think having a separate command would make sense.  That way you can access it without having to have a plot come up.

**Comment by DidierRLopes** [comment]
> > Was about to say the same. I don't think TA is the right menu to contain this. I would just have it in candle directly and allow a --raw command. Think is the right thing to do. At least that's what we've been doing for all other commands when we want raw data from a plot we see or so
> 
> I think having a separate command would make sense. That way you can access it without having to have a plot come up.

We don't need to have an AND condition, I was suggesting a OR. I.e. if the user adds `--raw` there's no plot popping. Which is exactly the same as adding a new command and removes complexity

**Comment by jmaslek** [comment]
> We don't need to have an AND condition, I was suggesting a OR. I.e. if the user adds `--raw` there's no plot popping. Which is exactly the same as adding a new command and removes complexity

I think the separate command makes more sense, since if you want to do raw and sort by a column, that is two flags instead of 1 not to mention on the plot command.  So could get confusing.

**Comment by DidierRLopes** [comment]
> > We don't need to have an AND condition, I was suggesting a OR. I.e. if the user adds `--raw` there's no plot popping. Which is exactly the same as adding a new command and removes complexity
> 
> I think the separate command makes more sense, since if you want to do raw and sort by a column, that is two flags instead of 1 not to mention on the plot command. So could get confusing.

We already do that in other commands. I just don't like adding a new command for the same data. I think doing 
```
candle --raw -s o
```
where o is for open.

is almost the same as
```
raw -s o
```

This is assuming that this feature is used by let's say 1% of users. If we start having a lot usage for it, I think it makes sense being a command. And I think that command should live on quantitative analysis menu. What you think?

**Comment by DidierRLopes** [comment]
> Agree. Could also add a raw flag to candle in addition

True. I'm happy with that :) 

So the OP will get this feature twice 😄

**Comment by colin99d** [comment]
> So I personally see more value as it's own command (as per the issue being addressed)
> 
> Just right under candle in the menu and you can do as you say (I'd probably go with hist instead of raw)
> 
> "hist c,v -n 20 --export"
> 
> Any input from the issue creator (I can't tag them)

hist is already in use

**Pull request merged**
