### PR TITLE
[🕹️]Added the notebook for currency exchange rate prediction

### LINKED ISSUE #6716: [🕹️] Create a Notebook for Currency Exchange Rate Forecasting
# 📄 Task
  
Build a notebook that predicts currency exchange rate movements based on historical data from OpenBB.

Feel free to utilize the [openbb-forecast](https://github.com/OpenBB-finance/openbb-forecast) extension.

---

### 📋 Requirements:

1. **Template**: Start by copying the [example template notebook](https://github.com/OpenBB-finance/OpenBB/blob/develop/examples/COMMUNITY_EXAMPLE_TEMPLATE.ipynb).
2. **Content**: 
   - Give your notebook a meaningful name.
   - Fill in the details in the template, including the notebook title, description, your GitHub username, the notebook name in the Google Colab button, and any additional sections relevant to the task.
   - Write code that uses OpenBB's features to model risk-return tradeoffs.
   - If your notebook requires additional dependencies, please specify those.
3. **Testing**: Ensure that all cells in the notebook run successfully and produce the intended results.
4. **Documentation**: Comment your code and add markdown cells where necessary to provide explanations for the analysis.
5. **Output**: The final notebook should be added to the `examples` folder in this repository.

### 💡 Tips:
  
- Refer to the [OpenBB Documentation](https://docs.openbb.co/) for guidance on using OpenBB features.

### 📬 Submission:

- Follow the submission instructions [here](https://github.com/OpenBB-finance/OpenBB/tree/develop/oss.gg).
- Open a Pull Request (PR) to the `develop` branch.
- Include a brief description of your notebook and the analysis it performs in the PR body.

Happy hacking!

### PR DESCRIPTION
**Pull request by Manish-k723**
### 1. **Why?:**

To contribute an enhanced feature to OpenBB that improves forex prediction using various time series models and to showcase it in a notebook format for ease of understanding and usage.

### 2. **What?:** 

Implemented a notebook demonstrating the usage of ARIMA, SARIMAX, Exponential Smoothing, and LSTM models for predicting forex prices based on historical data.

### 3. **Impact:**  
- Enables users to better forecast currency exchange rates using multiple models.
- Improves model selection flexibility for time series analysis.

### 4. **Testing Done:**  
Validated with historical forex data from OpenBB, comparing the actual prices to the predicted ones across all models used.

### 5. **Reviewer Notes:**  
I would appreciate any constructive feedback on this PR. If there are any areas for improvement, please share your insights by raising the issues. This will help in refining the changes rather than closing the PR prematurely.

closes #6716

### CODE REVIEW

**Comment by jmaslek** [comment]
Nice work

**Comment by Manish-k723** [comment]
Hey @jmaslek if you find this work useful, pls merge this PR and close it, I want to work on other issues as well on open-bb, but I can't get them assigned as I have an open PR. Pls help in this.

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
