### PR TITLE
Enhances `stocks/quote` to allow for multiple tickers

### PR DESCRIPTION
**Pull request by deeleeramone**
# Description

This PR is for improving the `stocks/quote` command to allow for querying multiple tickers.  The additional motivation for this change is to facilitate the ability to add watch list functionality.

The SDK has been updated to include, `openbb.stocks.quote_chart()`, and the docstrings have been updated to reflect the changes to the syntax requiring the tickers to be entered as a list for the model and view.

The Equity Report file has been updated to include the change in syntax to the SDK function.

**Note**:  Additional `--source` will be included in a future PR to allow this command to operate without any API keys required.

```console
quote AAPL,META,MSFT,GOOG,NFLX,AMZN
```

Screenshot 2023-04-28 at 11 51 12 AM

The index strings are now formatted as a title.

Screenshot 2023-04-28 at 1 46 53 PM

- [X] Summary of the change / bug fix.
- [X] Screenshot of the feature or the bug before/after fix, if applicable.
- [X] Relevant motivation and context.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.

Additional unit tests have been added capturing multiple tickers, and as well as the handling for a bad ticker.

* Provide instructions so we can reproduce.

`pytest tests/openbb_terminal/stocks/test_stocks_helper.py`

* Please also list any relevant details for your test configuration.

The integration test for the stocks menu has been updated to include multi-ticker quotes.

- [X] Make sure affected commands still run in terminal
- [X] Ensure the SDK still works
- [X] Check any related reports

# Checklist:

- [X] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [X] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [X] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [X] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [X] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by deeleeramone** [comment]
@jmaslek, any idea why running `python generate_sdk.py` added a bunch of empty lines to `sdk_helper.py`?

**Comment by jmaslek** [comment]
> @jmaslek, any idea why running `python generate_sdk.py` added a bunch of empty lines to `sdk_helper.py`?
> 
> Screenshot 2023-04-30 092511

not sure.  Probably something with formatting.  Surprised black didnt get rid of them.  Did you have to manually get rid of them ?

**Comment by deeleeramone** [comment]
>  Probably something with formatting. Surprised black didnt get rid of them. Did you have to manually get rid of them ?

Yes, manually deleted them.

**Comment by jmaslek** [comment]
You need to add some logic for if a string is added in.  This will split it by letters

```
In [3]: openbb.stocks.quote("AAPL")
Out[3]: 
Symbol                                          A                           A                    P                    L
Name                   Agilent Technologies, Inc.  Agilent Technologies, Inc.  Pandora Media, Inc.    Loews Corporation
Price                                      136.35                      136.35                  NaN                60.13
Changes Percentage                         0.6793                      0.6793                  NaN               4.4468
```

**Comment by deeleeramone** [comment]
> You need to add some logic for if a string is added in. This will split it by letters

Done! Added a caveat:

```
symbol = symbols if isinstance(symbols, list) is False else ",".join(symbols)
```

```
In [1]: from openbb_terminal.sdk import openbb

In [2]: openbb.stocks.quote('AAPL')
Out[2]: 
Symbol                                AAPL
Name                            Apple Inc.
Price                               169.59
Changes Percentage                  -0.053
Change                               -0.09
Day Low                             168.64
Day High                            170.45
Year High                           176.15
Year Low                            124.17
Market Cap                         2.683 T
Price Avg50                        157.903
Price Avg200                     150.89626
Exchange                            NASDAQ
Volume                            47.584 M
Avg Volume                        61989696
Open                                169.28
Previous Close                      169.68
Eps                                   5.89
Pe                                   28.79
Earnings Announcement  2023-05-04 20:00:00
Shares Outstanding                15.822 B
Timestamp              2023-05-01 13:00:04

In [3]: openbb.stocks.quote('AAPL,MSFT')
Out[3]: 
Symbol                                AAPL                   MSFT
Name                            Apple Inc.  Microsoft Corporation
Price                               169.59                 305.56
Changes Percentage                  -0.053                -0.5533
Change                               -0.09                   -1.7
Day Low                             168.64                 305.15
Day High                            170.45                  308.6
Year High                           176.15                 308.93
Year Low                            124.17                 213.43
Market Cap                         2.683 T                2.272 T
Price Avg50                        157.903               272.9444
Price Avg200                     150.89626               256.1089
Exchange                            NASDAQ                 NASDAQ
Volume                            47.584 M               20.749 M
Avg Volume                        61989696               31388708
Open                                169.28                 306.97
Previous Close                      169.68                 307.26
Eps                                   5.89                   9.22
Pe                                   28.79                  33.14
Earnings Announcement  2023-05-04 20:00:00    2023-07-24 10:59:00
Shares Outstanding                15.822 B                7.435 B
Timestamp              2023-05-01 13:00:04    2023-05-01 13:00:04

In [4]: openbb.stocks.quote(['AAPL,MSFT'])
Out[4]: 
Symbol                                AAPL                   MSFT
Name                            Apple Inc.  Microsoft Corporation
Price                               169.59                 305.56
Changes Percentage                  -0.053                -0.5533
Change                               -0.09                   -1.7
Day Low                             168.64                 305.15
Day High                            170.45                  308.6
Year High                           176.15                 308.93
Year Low                            124.17                 213.43
Market Cap                         2.683 T                2.272 T
Price Avg50                        157.903               272.9444
Price Avg200                     150.89626               256.1089
Exchange                            NASDAQ                 NASDAQ
Volume                            47.584 M               20.749 M
Avg Volume                        61989696               31388708
Open                                169.28                 306.97
Previous Close                      169.68                 307.26
Eps                                   5.89                   9.22
Pe                                   28.79                  33.14
Earnings Announcement  2023-05-04 20:00:00    2023-07-24 10:59:00
Shares Outstanding                15.822 B                7.435 B
Timestamp              2023-05-01 13:00:04    2023-05-01 13:00:04
```

btw, @jmaslek, every function with a list as an input currently does this. 

Screenshot 2023-05-01 at 3 13 19 PM

Screenshot 2023-05-01 at 3 14 33 PM

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
